title: Consultoria Wave
description: Somos especialistas em Acústica e Vibrações para projetar soluções, visando o conforto acústico do cliente.
keywords: Consultoria, Wave, Sonorização, Acústica, Acústico, Som, Ambiente, Certificado
url: "https://www.consultoriawave.com"
baseurl: ""
city: "Florianópolis-SC"
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
paginate: 7
pagination_path: "/:num"
google_analytics: "UA-105738007-1"
formspree_id: "mpzevbjq"

exclude:
  - _antigas
  - template
  - docker-compose.yml

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

sass:
  style: compressed

empresa:
  telefone: 
    link: 005548999076388
    formated: +55 48 99907-6388
  email: contato@consultoriawave.com
  social:
    facebook: CONSULTORIAWAVE
    instagram: waveconsultoria
  endereco: "Av. Santa Catarina, n° 1619<br>Balneário, Florianópolis SC"