title: Consultoria Wave
description: A empresa possui corpo técnico capacitado para solucionar a necessidade do cliente, visando o conforto acústico em qualquer tipo de ambiente, seja residencial, industrial ou de lazer.
keywords: Consultoria, Wave, Sonorização, Acústica, Acústico, Som, Ambiente, Certificado
url: "https://www.consultoriawave.com"
baseurl: ""
city: "Florianópolis-SC"
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
paginate: 7
pagination_path: "/:num"
google_analytics: "UA-105738007-1"

exclude:
  - bin
  - docker-compose.yml
  - template

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

sass:
  style: compressed

empresa:
  telefone: 
    link: 005548999076388
    formated: +55 48 99907-6388
  email: contato@consultoriawave.com
  social:
    facebook: CONSULTORIAWAVE
    instagram: waveconsultoria
  endereco: "Av. Santa Catarina, n° 1619<br>Balneário, Florianópolis SC"